- apiVersion: developer.microsoft.com/v1
  kind: Repository
  metadata:
    name: shoppingCartDemo
    namespace: contoso-inc
    provider: github.com
    title: shoppingCartDemo
  relations:
    - type: Squad
      target: contoso-inc/contoso-inc.engineering/eCommDevSquad
    - type: Environment
      target: Environment:devcenter.azure.com/devplatformcenter/Project-Alpha/Project-Alpha-mdw-ecomm-integration
    - type: operation
      target: Operation:devcenter.azure.com/devplatformcenter/Project-Alpha-mdw-ecomm-integration
