- apiVersion: developer.microsoft.com/v1
  kind: Squad
  metadata:
    name: eCommDevSquad
    namespace: contoso-inc.engineering
    title: eCommDevSquad
    description: Developers working on eCommerce platform
    provider: contoso-inc
  spec:
    type: squadDefinition
    id: /Contoso-Inc/eCommDevSquad
    businessUnit: EC-234i
    members:
      - markweitzel
      - thomasdolby
      - rufusdusol
      - danielsol
      - dennislloyd
  relations: 
    - type: Repository
      target: 'repo:github.com/contoso-inc/shoppingCartDemo'
    - type: Template
      target: 'template:github.com/Contoso-Inc/todo-java-mongo-aca'
