- apiVersion: developer.microsoft.com/v1
  kind: Resource
  metadata:
    name: rg-mdwtodotest
    namespace: contoso-inc.azure
    title: mdwShoppingCartTest
    description: Azure Resource Group
    provider: plateng.azure.microsoft
  spec:
    type: azureResourceGroup
    id: /subscriptions/2554f64d-0419-4e39-8121-5e01270578ea/resourceGroups/rg-mdwtodotest
  relations: 
    - type: Repository
      target: 'repo:github.com/contoso-inc/shoppingCartDemo'
    - type: Template
      target: 'template:github.com/Contoso-Inc/todo-java-mongo-aca'
    - type: Resource
      target: 'resource:/subscriptions/2554f64d-0419-4e39-8121-5e01270578ea/resourceGroups/rg-mdwtodo/providers/Microsoft.ContainerRegistry/registries/crsltnoo2bdgv2o'